[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "httpx",
    "pydantic",
    "pydantic-settings>=2.15.0",
    "pytest",
    "ruff",
    "sqlalchemy",
    "uvicorn",
]

[dependency-groups]
dev = [
    "pytest-cov>=7.1.0",
]
